"""Exact algebraic checks for the Schur form and the symbol condition (Section 2 of the note).

All computations are exact (sympy rationals and algebraic numbers); no sampling and no figures.
The checks are algebraic at a point: they do not control terms containing the derivative of the embedding.

Checks:
  C1  P^2 = P iff Pi is a partial isometry (Pi Pi^* Pi = Pi), on explicit examples.
  C2  For a contraction that is not a partial isometry, 1 - P >= 0 and Pi D (1-P) D Pi^* = N^dagger N with
      N = (1-P)^{1/2} D Pi^*, for D a Hermitian symbol matrix.
  C3  The four Euclidean Clifford generators on C^4 generate the full matrix algebra (dimension 16), so the action is
      irreducible; consequently no proper non-zero subspace is stable.
  C4  Symbol condition on an irreducible fibre: for an isometric Pi^* of rank 2 the subspace R = Im Pi^* is not
      gamma-invariant and R together with its gamma-images spans C^4, so (1-P)^{1/2} gamma Pi^* = 0 fails (P != 1).
  C5  Reducible fibre C^4 (x) C^2 with a constant embedding Pi^* = 1 (x) iota: the symbol condition holds and N = 0.
"""

import itertools
import sympy as sp

I = sp.I


def kron(a, b):
    return sp.kronecker_product(a, b)


def clifford_generators():
    """Four Hermitian anticommuting 4x4 matrices with g_mu^2 = 1."""
    sx = sp.Matrix([[0, 1], [1, 0]])
    sy = sp.Matrix([[0, -I], [I, 0]])
    sz = sp.Matrix([[1, 0], [0, -1]])
    one = sp.eye(2)
    return [kron(sx, sx), kron(sx, sy), kron(sx, sz), kron(sy, one)]


def algebra_dimension(gens):
    """Dimension of the unital algebra generated by the matrices, by closure of monomials."""
    n = gens[0].shape[0]
    basis = [sp.eye(n)]
    changed = True

    def rank_of(mats):
        rows = [list(m.reshape(1, n * n)) for m in mats]
        return sp.Matrix(rows).rank()

    current = rank_of(basis)
    while changed:
        changed = False
        for b, g in itertools.product(list(basis), gens):
            cand = (g * b).applyfunc(sp.simplify)
            if rank_of(basis + [cand]) > current:
                basis.append(cand)
                current += 1
                changed = True
    return current


def check_c1():
    # partial isometry: Pi = [[1, 0, 0]] : C^3 -> C^1 is a coisometry, P projector, Pi Pi^* = 1
    Pi = sp.Matrix([[1, 0, 0]])
    P = Pi.H * Pi
    assert (P * P - P).is_zero_matrix
    assert (Pi * Pi.H * Pi - Pi).is_zero_matrix
    # partial isometry that is not onto: C^2 -> C^2, Pi = diag(1, 0)
    Pi = sp.diag(1, 0)
    P = Pi.H * Pi
    assert (P * P - P).is_zero_matrix and (Pi * Pi.H * Pi - Pi).is_zero_matrix
    assert not (Pi * Pi.H - sp.eye(2)).is_zero_matrix
    # contraction, not a partial isometry
    Pi = sp.diag(1, sp.Rational(1, 2))
    P = Pi.H * Pi
    assert not (P * P - P).is_zero_matrix and not (Pi * Pi.H * Pi - Pi).is_zero_matrix
    print("C1 ok")


def check_c2():
    gens = clifford_generators()
    xi = [sp.Rational(1), sp.Rational(2), sp.Rational(-1), sp.Rational(3)]
    D = sum((x * g for x, g in zip(xi, gens)), sp.zeros(4, 4))
    # Pi: C^4 -> C^2 contraction, not a partial isometry
    Pi = sp.Matrix([[1, 0, 0, 0], [0, sp.Rational(1, 2), 0, 0]])
    P = Pi.H * Pi
    one_minus_P = sp.eye(4) - P
    assert all(e >= 0 for e in one_minus_P.eigenvals())
    root = sp.diag(*[sp.sqrt(one_minus_P[i, i]) for i in range(4)])  # diagonal in this example
    N = root * D * Pi.H
    lhs = Pi * D * one_minus_P * D * Pi.H
    rhs = N.H * N
    assert (lhs - rhs).applyfunc(sp.simplify).is_zero_matrix
    assert not (P * P - P).is_zero_matrix
    print("C2 ok")


def check_c3_c4():
    gens = clifford_generators()
    for a, b in itertools.combinations(range(4), 2):
        assert (gens[a] * gens[b] + gens[b] * gens[a]).is_zero_matrix
    for g in gens:
        assert (g * g - sp.eye(4)).is_zero_matrix
    dim = algebra_dimension(gens)
    assert dim == 16, dim
    print("C3 ok (algebra dimension 16)")
    # C4: isometric Pi^* of rank 2 on the irreducible fibre C^4.
    PiStar = sp.Matrix([[1, 0], [0, 1], [0, 0], [0, 0]])
    R = PiStar
    P = PiStar * PiStar.H
    one_minus_P = sp.eye(4) - P
    # The symbol condition requires gamma(xi) R to lie in K = ker(1-P), which is contained in R: R would be
    # invariant under every gamma. Check that R is NOT invariant, and that R together with its images spans C^4.
    stacked = sp.Matrix.hstack(R, *[g * R for g in gens])
    assert stacked.rank() == 4
    assert any(sp.Matrix.hstack(R, g * R).rank() > 2 for g in gens)
    assert any(not ((one_minus_P) * g * PiStar).is_zero_matrix for g in gens)
    print("C4 ok (R and its gamma-images span C^4, R is not gamma-invariant; the symbol condition fails with P != 1)")


def check_c5():
    gens = clifford_generators()
    gens2 = [kron(g, sp.eye(2)) for g in gens]
    iota = sp.Matrix([[1], [0]])
    PiStar = kron(sp.eye(4), iota)
    P = PiStar * PiStar.H
    one_minus_P = sp.eye(8) - P
    for g in gens2:
        assert ((one_minus_P) * g * PiStar).is_zero_matrix
    print("C5 ok (symbol condition holds on a reducible fibre; N = 0 for the constant embedding)")


if __name__ == "__main__":
    check_c1()
    check_c2()
    check_c3_c4()
    check_c5()
